### ISSUE TITLE
silence spotbugs warnings 

### ISSUE THREAD

**Issue by soloturn** [spotbugs/spotbugs-gradle-plugin#1018]
i tried to silence a spotbugs warning with:

```
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;

        @SuppressFBWarnings
        private T t;
```

but the dependency is not known. can you pleaes include it into the plugin so one does not need it extra in the project?

**Comment by C-Otto** [comment]
The dependency needs to be available at compile time, otherwise the code won't compile. Spotbugs brings in its own dependencies which are needed for the analysis, i.e. at runtime of the scan. These are two very different scopes and should not be mixed.

Furthermore, handling some project's (compile) dependencies can be very involved and needs to be handled with care. I personally don't want some "random" plugin mess with my project's dependencies, just so that some optional feature works. This plugin's purpose is to make "spotbugs" run. Running spotbugs and tweaking your code to please spotbugs (or make spotbugs ignore certain issues) are two different things, which is why I think this is out of scope.

I suggest a) that you, @soloturn, add the dependency yourself, b) to close the issue ("won't do").

**Comment by soloturn** [comment]
that would be then a problem of all other software as well where warnings can be silenced, like pmd, checkstyle, sonar, .... what makes spotbugs special?

**Comment by KengoTODA** [comment]
There is nothing special. SpotBugs provides own annotations so if you want to annotate your code with it, you need to add the annotation artifact via `compileOnly` dependency.

And actually `java.lang.SuppressWarnings` also works even for SpotBugs. [SpotBugs has a longer history than `java.lang.SuppressWarnings`](https://github.com/spotbugs/spotbugs/blob/0f7a97f828c3e48bbb97cea636f9be14afb745c7/spotbugs-annotations/src/main/java/edu/umd/cs/findbugs/annotations/SuppressWarnings.java#L28) so it has its own annotation, but [it does not mean that SpotBugs users are forced to use `SuppressFBWarnings`](https://github.com/spotbugs/spotbugs/blob/0f7a97f828c3e48bbb97cea636f9be14afb745c7/spotbugs/src/main/java/edu/umd/cs/findbugs/detect/NoteSuppressedWarnings.java#L98-L100). 

Anyway your doubt is unrelated to this Gradle plugin so that I will close this issue. If you still have doubts to ask, [open a discussion at `spotbugs/spotbugs` project](https://github.com/spotbugs/spotbugs/discussions).
