### ISSUE TITLE
4.0.0 no longer included in "check"

### ISSUE THREAD

**Issue by ctmay4** [spotbugs/spotbugs-gradle-plugin#196]
If I update the plugin version from 3.0.0 to 4.0.0, `spotbugMain` and `spotBugsTest` no longer run as part of the `check` task.  They work if I run the tasks manually, but they used to be included as a verification step.  I looked through the changelog and did not see anything.  Was this intentional?

**Comment by lazystone** [comment]
@KengoTODA  I tried 4.0.1 - it does not seem to be fixed  there

**Comment by ctmay4** [comment]
I tried as well and it did not fix the issue for me.

**Comment by KengoTODA** [comment]
could you try to share [mcve](https://stackoverflow.com/help/minimal-reproducible-example)? It's nice if you can make it as a functional test in this repo :pray:

**Comment by lazystone** [comment]
@KengoTODA [here you go](https://github.com/lazystone/spotbugs-bugs).

In order to run spotbugs I have to use this: https://github.com/lazystone/spotbugs-bugs/blob/master/build.gradle.kts#L40

Also side question: Is [this](https://github.com/lazystone/spotbugs-bugs/blob/master/build.gradle.kts#L34-L36) a correct kotlin snippet to enable html reports?

**Comment by KengoTODA** [comment]
@lazystone I'm not sure about the Kotlin script, but you can refer the official document of JaCoCo plugin that has similar API to ours:
https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_report_configuration

When you found proper way, consider to submit PR to share it with other users :+1:

note: our implementation does not implement `Reporting` interface because `DefaultReportContainer` is internal so it's difficult to create `SpotBugsReportContainer` like [the JaCoCo's one](https://github.com/gradle/gradle/blob/a799cabc0d4dbe15c4a6f476bf86498ac45b4c3b/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoReportsContainer.java).

**Comment by KengoTODA** [comment]
@lazystone Thanks for your share! It seems that our Gradle plugin cannot find the `check` task, I can see the following debug log:

> 2020-03-09T11:39:27.097+0800 [DEBUG] [com.github.spotbugs.snom.SpotBugsPlugin] check task not found

I'll find why.

**Comment by KengoTODA** [comment]
The minimal case for reproduction is here:

```kotlin
// `./gradlew check -i` does not run `spotbugsMain` task
plugins {
    id("com.github.spotbugs") version "4.0.1"
    java
}

repositories {
    mavenCentral()
}
```

However I cannot reproduce it by functional test case which runs on spock.

**Comment by ctmay4** [comment]
Sorry I took so long and maybe you don't need it anymore, but I put together a minimal example in a repository.

https://github.com/ctmay4/spotbugs-plugin-check

Let me know if you need anything else.

**Comment by KengoTODA** [comment]
@ctmay4 I confirmed that `4.0.2` runs `spotbugsMain` task by `./gradlew check`.
Here is the patch:

```patch
diff --git a/build.gradle b/build.gradle
index 2dbed34..feff69a 100644
--- a/build.gradle
+++ b/build.gradle
@@ -1,7 +1,7 @@
 plugins {
     id 'java'
     id 'application'
-    id "com.github.spotbugs" version "3.0.0"
+    id "com.github.spotbugs" version "4.0.2"
 }

 repositories {
```

**Comment by KengoTODA** [comment]
@lazystone it should work even to your case, I confirmed with the following patch:

```patch
diff --git a/build.gradle.kts b/build.gradle.kts
index ec5e689..e7cc844 100644
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -1,6 +1,6 @@
 plugins {
     // https://github.com/spotbugs/spotbugs-gradle-plugin
-    id("com.github.spotbugs") version "4.0.1"
+    id("com.github.spotbugs") version "4.0.2"

     java
     idea
```


We still have #198, though...

**Comment by ctmay4** [comment]
Thanks.,  It does run it.  It runs it in a different order than before.  It used to run it in the same place a other tools like Checkstyle which is before the tests start.  Now it runs it after the tests.  

I don't think it matters, but I did want to point it out.

### 3.0.0

```
Testing started at 8:23 AM ...
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :spotbugsMain UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :spotbugsTest UP-TO-DATE
> Task :test UP-TO-DATE
> Task :check UP-TO-DATE
BUILD SUCCESSFUL in 227ms
5 actionable tasks: 5 up-to-date
8:23:07 AM: Task execution finished 'check'.
```

### 4.0.2

```
Testing started at 8:21 AM ...
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test UP-TO-DATE
> Task :spotbugsMain
> Task :spotbugsTest
The following classes needed for analysis were missing:
  spotbugs.plugin.check.App
> Task :check
BUILD SUCCESSFUL in 4s
5 actionable tasks: 2 executed, 3 up-to-date
8:21:21 AM: Task execution finished 'check'.
```

**Comment by KengoTODA** [comment]
Thanks, now we use Worker API for better performance, ot could be the reason.
