### ISSUE TITLE
4.0.2 spotbugs-gradle-plugin does not work with freefair lombok plugin

### ISSUE THREAD

**Issue by quotidian-ennui** [spotbugs/spotbugs-gradle-plugin#206]
This is the project : 

https://github.com/adaptris/interlok-nats/tree/spotbugs-gradle-4.0

We're using the freefair lombok plugin using lombok to reduce the amount of "clutter" in our java-code

spotbugs-gradle-plugin 3.0.0 works fine as is (check the develop branch); however, the 4.0.2 plugin fails.

```
lchan@phooey MINGW64 /c/adaptris/work/dev/nats (spotbugs-gradle-4.0)
$ ./gradlew compileJava

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\adaptris\work\dev\nats\build.gradle' line: 5

* What went wrong:
An exception occurred applying plugin request [id: 'java']
> Failed to apply plugin [id 'org.gradle.java']
   > com.github.spotbugs.snom.SpotBugsExtension_Decorated cannot be cast to org.gradle.api.plugins.quality.CodeQualityExtension

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 767ms
```

The changes in the branch are : 

* Upgraded to gradle 6.2.2 (since we were running 5.6.3)
* Switch to just a spotbugsMain{} section rather than a tasks.withType() since you've changed the package name.
* It's running with Java8 : 

```
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (Zulu 8.44.0.11-CA-win64) (build 1.8.0_242-b20)
OpenJDK 64-Bit Server VM (Zulu 8.44.0.11-CA-win64) (build 25.242-b20, mixed mode)
```

Note that we can upgrade other projects that don't use lombok to the 4.0.2 plugin; using Java 8 + gradle 5.6.3

**Comment by quotidian-ennui** [comment]
I checked the src code and it's because the groovy task extends DefaultTask, and doesn't extend CodeQualityExtension.

**Comment by KengoTODA** [comment]
Currently our extension does not depend on `CodeQualityExtension`. because:

1. The [setSourceSets() API introduces hidden dependency in build script](https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/issues/97#issuecomment-587244680) and it makes build unstable unexpectedly.
2. It lacks documentation. Even though it's not put into `internal` package, it actually behaves Gradle internal one. Gradle sometimes changes behavior of public API ([example](https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/pull/54#issuecomment-575328248)) so it's better to stop depending on nonessential API, in my feeling.
3. I think `setSourceSets()` API is not proper in the manner of recent Gradle. It should receive `ListProperty<SourceSet>`. Gradle could bring breaking change here.

This plugin is initially forked from Gradle official plugin, but it's now re-implemented from scratch, then has less motivation to extend `CodeQualityExtension`. Could you propose a fix to the freefair lombok plugin side? Thanks for your understanding!

**Comment by yuriy-slobodchikov** [comment]
Hello, please could you explain is there another similar bug about Lombok and spotbugs gradle plugin? why this ticket is closed?

**Comment by psxpaul** [comment]
@yuriy-slobodchikov I opened the above ticket with the lombok plugin, and it looks like they've committed a fix for this issue on their end. I imagine this will be fixed whenever they release a new lombok plugin version.
