### ISSUE TITLE
Plugin cannot be resolved

### ISSUE THREAD

**Issue by daggerok** [spotbugs/spotbugs-gradle-plugin#212]
Hi

Gradle portal says that latest version is 4.0.4
![image](https://user-images.githubusercontent.com/2445604/77099345-71da9380-6a1c-11ea-9086-bc68b83006cc.png)

but this is what I can see:
![image](https://user-images.githubusercontent.com/2445604/77099274-553e5b80-6a1c-11ea-8343-69dcb0af47cf.png)

and my old way resolution doesnt worked for 4.0.4:

```groovy
// see: https://github.com/spotbugs/spotbugs-gradle-plugin/issues/32
// another issue waiting for fix: https://github.com/spotbugs/spotbugs-gradle-plugin/issues/94

buildscript {
  repositories {
    maven { url "https://plugins.gradle.org/m2/" }
    gradlePluginPortal()
    mavenCentral()
    jcenter()
  }
  dependencies {
    classpath("gradle.plugin.com.github.spotbugs:spotbugs-gradle-plugin:$spotbugsPluginVersion")
  }
}

subprojects {
  apply plugin: 'com.github.spotbugs'

  repositories {
    maven { url "https://plugins.gradle.org/m2/" }
    gradlePluginPortal()
    mavenCentral()
    jcenter()
  }

  spotbugs {
    toolVersion = project.spotbugsToolVersion
    effort = 'max'
    ignoreFailures = project.findProperty('failOnBugs') ?: false
  }

  tasks.withType(com.github.spotbugs.SpotBugsTask) {
    reports {
      html {
        enabled = true
      }
      xml {
        enabled = false
      }
    }
  }
}
```

Only 2.0.0 is latest worked version for me...
I'm using gradle 6.2.2
How I can workaround that?

Thanks!

---
Thanks

**Comment by chadlwilson** [comment]
Note that the classpath/package has changed in 4.0.0 as you can see in the examples on the plugin portal that you paste above, as well as the changelog of the plugin.

https://plugins.gradle.org/m2/gradle/plugin/com/github/spotbugs/snom/spotbugs-gradle-plugin/

Moving to the plugins DSL rather than the legacy way of defining Gradle plugins might make this step easier (because the plugin ID hasn't changed); but seems you will also have to change the `tasks.WithType` line to the new package in either case. Same for your issue with `3.0.0` - that also seemed to have a different classpath for the plugin jar than the one you have above...

**Comment by daggerok** [comment]
Oh.. seems like `snom` is missing in my case, thanks, I'll try use correct groupId on Monday and let you know.

Thanks

**Comment by daggerok** [comment]
Okay, I have checked and seems like its impossible to configure multi-module project with 4.x version of gradle plugin, like from my first post...

its possible to configure 2.0.0 plugin + spotbugs tool version 4.0.1, but not with plugin 4.0.4...

Can you please provide worked example for multi-module spotbugs gradle plugin 4.0.4 version?

Thanks

---
Regards,

**Comment by chadlwilson** [comment]
I'm just another community user, and don't use it via a multi-module setup, so afraid personally I can't help there.

**Comment by KengoTODA** [comment]
The major topic of this issue is already resolved, so I'll close this issue.
About the multi-module config, use #121 for coming discussion.
