### ISSUE TITLE
MissingPropertyException when setting effort of SpotBugsExtension

### ISSUE THREAD

**Issue by daanschipper** [spotbugs/spotbugs-gradle-plugin#387]
When optimizing the configuration time using the gradle-profiler and checking the flame graph output I noticed the `SpotBugsExtension.setEffort()` method throwing `MissingPropertyException`s. I'm using `project.getExtensions().getByType(SpotBugsExtension.class).setEffort("max")` to set the effort. 

It's this line [`Effort effort = name == null ? null : Effort.valueOf(name.toUpperCase())`](https://github.com/spotbugs/spotbugs-gradle-plugin/blob/fd232f92e1c1750291b732563a879d7629cb11a2/src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy#L199) causing the exception, but I don't have enough Groovy knowledge to understand why it is throwing the `MissingPropertyException`.

Here you can see the time it takes to apply the Spotbugs plugin and configure basic stuff of the extension. One third of the time is spent with `SpotbugsExtension.setEffort()`.

<img width="1192" alt="Screenshot 2020-11-20 at 17 06 03" src="https://user-images.githubusercontent.com/2778477/99821752-b477e100-2b52-11eb-9af1-60acf39e5921.png">

Unfortunately I cannot share the full stacktrace, but this is the final part of the stacktrace:

```
invokeStaticMissingProperty:1021, MetaClassImpl (groovy.lang)
getProperty:1866, MetaClassImpl (groovy.lang)
getProperty:1842, MetaClassImpl (groovy.lang)
invokeStaticMethod:1474, MetaClassImpl (groovy.lang)
callStatic:62, StaticMetaClassSite (org.codehaus.groovy.runtime.callsite)
callStatic:216, AbstractCallSite (org.codehaus.groovy.runtime.callsite)
valueOf:-1, Effort (com.github.spotbugs.snom)
call:-1, Effort$valueOf (com.github.spotbugs.snom)
setEffort:192, SpotBugsExtension (com.github.spotbugs.snom)
```

Environment:
Gradle 6.7
Java openjdk 11.0.6 2020-01-14
Spotbugs gradle plugin 4.5.0

**Comment by jscancella** [comment]
I would think this would cause your build to fail since it is throwing an exception. Looking at the stack trace it seems it is somehow trying to set the `effort` to `-1`?

**Comment by daanschipper** [comment]
Some dynamic groovy calls are happening, the exception is silently caught in `MetaClassImpl`
```
try {
    prop = this.getProperty(this.theClass, this.theClass, methodName, false, false);
} catch (MissingPropertyException var13) {
}
```

**Comment by jscancella** [comment]
Does this happen if instead of using `project.getExtensions().getByType(SpotBugsExtension.class).setEffort("max")` you use something like
```
spotbugs {
  effort = 'max'
}
``` 
?

**Comment by daanschipper** [comment]
Yes, it hits the exact same function`SpotBugsExtension.setEffort()`.

**Comment by jscancella** [comment]
so ` Effort effort = name == null ? null : Effort.valueOf(name.toUpperCase())` is just another way to write
```
Effort effort = null;
if(name != null){
     effort = Effort.valueOf(name.toUpperCase())
}
```
So the only way it is throwing an error there is if `name.toUpperCase()` doesn't equal any of the enum values in `Effort`.

With the intentional swallowing of the exception by Gradle, I feel like this is a bug on their end. Have you tried posted it on their forums or github?

**Comment by daanschipper** [comment]
I understand that part, is just very strange that groovy is throwing the `MissingPropertyException`. This issue is to find out if a different way of writing that statement is possible with groovy which does not throw the exception.

**Comment by KengoTODA** [comment]
I'm checking how Groovy executed the code.
Here I assume that the Gradle version is 2.5.12 used by the latest Gradle v6.7.1:

[invokeStaticMissingProperty:1021, MetaClassImpl (groovy.lang)](https://github.com/apache/groovy/blob/GROOVY_2_5_11/src/main/groovy/groovy/lang/MetaClassImpl.java#L1021)
[getProperty:1866, MetaClassImpl (groovy.lang)](https://github.com/apache/groovy/blob/GROOVY_2_5_11/src/main/groovy/groovy/lang/MetaClassImpl.java#L1866)
[getProperty:1842, MetaClassImpl (groovy.lang)](https://github.com/apache/groovy/blob/GROOVY_2_5_11/src/main/groovy/groovy/lang/MetaClassImpl.java#L1842)
[invokeStaticMethod:1474, MetaClassImpl (groovy.lang)](https://github.com/apache/groovy/blob/GROOVY_2_5_11/src/main/groovy/groovy/lang/MetaClassImpl.java#L1474)
[callStatic:62, StaticMetaClassSite (org.codehaus.groovy.runtime.callsite)](https://github.com/apache/groovy/blob/GROOVY_2_5_11/src/main/java/org/codehaus/groovy/runtime/callsite/StaticMetaClassSite.java#L62)
[callStatic:216, AbstractCallSite (org.codehaus.groovy.runtime.callsite)](https://github.com/apache/groovy/blob/GROOVY_2_5_11/src/main/java/org/codehaus/groovy/runtime/callsite/AbstractCallSite.java#L216)

The point is here: [MetaClassImpl catches and ignores MissingPropertyException](https://github.com/apache/groovy/blob/GROOVY_2_5_11/src/main/groovy/groovy/lang/MetaClassImpl.java#L1472-L1477). I also confirmed that this behaviour is not improved even [in the master branch](https://github.com/apache/groovy/blob/dbc49039ab7f424ab970990a55ccba9cba3a6876/src/main/java/groovy/lang/MetaClassImpl.java).

So @daanschipper I suggest you to [issue a report to Groovy language project](http://groovy-lang.org/reporting-issues.html). I tried the following solution, but I think it won't be solution because we still need to invoke a static method in `Effort` class.

```diff
diff --git a/src/main/groovy/com/github/spotbugs/snom/Effort.groovy b/src/main/groovy/com/github/spotbugs/snom/Effort.groovy
index 791ac9c..aff86a5 100644
--- a/src/main/groovy/com/github/spotbugs/snom/Effort.groovy
+++ b/src/main/groovy/com/github/spotbugs/snom/Effort.groovy
@@ -13,6 +13,8 @@
  */
 package com.github.spotbugs.snom;
 
+import edu.umd.cs.findbugs.annotations.NonNull
+
 /**
  * The {@code Effort} is configuration to adjust SpotBugs detectors. Use lower effort to reduce
  * computation cost.
@@ -50,5 +52,16 @@ enum Effort {
      * The effort level that maximize the computation cost. SpotBugs will run Interprocedural Analysis
      * of Referenced Classes.
      */
-    MAX
+    MAX;
+    static Effort fromString(@NonNull String string) {
+        Objects.requireNonNull(string)
+        switch (string.toUpperCase()) {
+            case "MIN": return MIN;
+            case "LESS": return LESS;
+            case "DEFAULT": return DEFAULT;
+            case "MORE": return MORE;
+            case "MAX": return MAX;
+            default: throw new IllegalArgumentException("'${string}' is not valid as Effort value")
+        }
+    }
 }
diff --git a/src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy b/src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy
index 20a4146..b0050ab 100644
--- a/src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy
+++ b/src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy
@@ -196,7 +196,7 @@ class SpotBugsExtension {
     }
 
     void setEffort(@Nullable String name) {
-        Effort effort = name == null ? null : Effort.valueOf(name.toUpperCase())
+        Effort effort = name == null ? null : Effort.fromString(name)
         getEffort().set(effort)
     }
```

**Comment by daanschipper** [comment]
`getEffort().set(Effort.MAX)` can be used to avoid this issue altogether.
