### ISSUE TITLE
'release' input causes build caching to be ineffective

### ISSUE THREAD

**Issue by DanielThomas** [spotbugs/spotbugs-gradle-plugin#538]
`SpotBugsTask` is a cacheable task, however the `release` input property makes caching ineffective for builds that have a version specified:

<img width="985" alt="Screen Shot 2021-08-04 at 4 44 45 pm" src="https://user-images.githubusercontent.com/1479220/128134445-8ae00d1b-a491-4912-995e-bdb82817819b.png">

**Comment by KengoTODA** [comment]
note: [release property of SpotBugsTask](https://github.com/spotbugs/spotbugs-gradle-plugin/blob/0f84a0449648147c429449facd061248395bef59/src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy#L204-L209) uses [release property of SpotBugsExtension](https://github.com/spotbugs/spotbugs-gradle-plugin/blob/0f84a0449648147c429449facd061248395bef59/src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy#L131-L135) as convention. And SpotBugsExtension uses non-standard way to configure the release property:

https://github.com/spotbugs/spotbugs-gradle-plugin/blob/0f84a0449648147c429449facd061248395bef59/src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy#L203-L211

It's necessary because [`Project#version` returns an `Object` type instance](https://docs.gradle.org/7.2/dsl/org.gradle.api.Project.html#org.gradle.api.Project:version) so cannot apply the [lazy configuration](https://docs.gradle.org/current/userguide/lazy_configuration.html).



It seems that some other plugins simply apply a `Provider` that resolves `project.version` [like this](https://github.com/gradle-nexus/publish-plugin/blob/f3c24a7b92c5b282fa921cb5f8c966aff6dbf306/src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishExtension.kt#L33-L35), but I'm not so sure that it works in all cases. I'll ask to the community later.

**Comment by DanielThomas** [comment]
@KengoTODA yeah, that should work for deferring evaluation of the property, but still breaks caching and incremental builds with dynamic versions. You ideally want `release` to not vary at all.

**Comment by KengoTODA** [comment]
🤔  The value of `release` is same to `project.version.toString()`, so I assume that in most cases it's not vary.

I guess I have some misunderstandings around the build cache...? Could you explain more about the problem and how we can fix it?

**Comment by KengoTODA** [comment]
One possible scenario: the build A run the cache key computation after `release.convention(...)` invocation, and the build B run it before `release.convention(...)` invocation.
This scenario can be solved if we can make the `release` property completely lazy.

**Comment by KengoTODA** [comment]
> with dynamic versions

maybe this is the key, what it means? Are you generating the `version` property in your build script?

**Comment by DanielThomas** [comment]
That's right - we version on the fly using https://github.com/nebula-plugins/nebula-release-plugin. Many projects continually release, so every push is a timestamped snapshot build, including the branch name for pull requests, and every main branch push either pushes release version incrementing minor/patch, or a release candidate in the form `x.x.x-rc.n` where `n` increments for every release. 

That means while a project might be completely up to date for compilation and the inputs to `SpotBugsTask` is completely unchanged, the project version being mapped to `release` means the task is not `UP-TO-DATE` where we have a warm workspace and an incremental build or misses the build cache.

**Comment by DanielThomas** [comment]
Oh, I should add - looks like we could workaround this by setting that value ourselves, just wanted to report this upstream in the event you want to address this in the plugin.

**Comment by KengoTODA** [comment]
Thanks for your share, then I think it's better to solve this problem by setting `release` property by your own. We use the value of this property when generate a report, so it's reasonable to invalidate the build cache when the value is changed. :)

**Comment by DanielThomas** [comment]
No worries, thanks for taking a look!
