### ISSUE TITLE
How to specify that all SpotBugs reports should have XML and HTML enabled?

### ISSUE THREAD

**Issue by jpschewe** [spotbugs/spotbugs-gradle-plugin#628]
Now that #114 has been completed via #623 I see that I can use the following to specify both reports
```java
spotbugsMain {
    reports {
      html {
        enabled = true
      }
      xml {
        enabled = true
      }
    }
}
spotbugsTest {
    reports {
      html {
        enabled = true
      }
      xml {
        enabled = true
      }
    }
}
spotbugsIntegrationTest {
    reports {
      html {
        enabled = true
      }
      xml {
        enabled = true
      }
    }
}
```

Is there a more compact way to specify that I want HTML and XML enabled for all SpotBugs tasks?

**Comment by KengoTODA** [comment]
One idea is configure all tasks via `tasks.withType` API:

```groovy
// build.gradle
tasks.withType(com.github.spotbugs.snom.SpotBugsTask) {
  reports {
    xml {
      enabled = true
    }
    html {
      enabled = true
    }
  }
}
```

or if you're using the RC release, it is suggested to use new API instead of deprecated `enabled` property:

```groovy
// build.gradle
tasks.withType(com.github.spotbugs.snom.SpotBugsTask) {
  reports {
    xml {
      required.set(true)
    }
    html {
      required.set(true)
    }
  }
}
```

Refer the [official document](https://docs.gradle.org/7.3/userguide/more_about_tasks.html#sec:locating_tasks) for detail of `tasks.withType` API.

**Comment by jpschewe** [comment]
Thank you, I wasn't sure about the correct syntax.
