### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by dovogt** [spotbugs/spotbugs-gradle-plugin#85]
Gradle 5.0 changed the memory settings. The following error occurs during execution:

Execution failed for task ':spotbugsMain'.
> A failure occurred while executing com.github.spotbugs.internal.spotbugs.SpotBugsRunner
   > GC overhead limit exceeded

I use it together with the ru.vyarus: gradle-quality-plugin

**Comment by KengoTODA** [comment]
Hi, do you mean [this change](https://github.com/gradle/gradle/commit/15a44197644f8ca57abab27336daef4179744dfb)? Could you share [mcve](https://stackoverflow.com/help/mcve) to reproduce your problem?

**Comment by dovogt** [comment]
Sorry for my late reply. Enclosed I send you the log file with debug output.
Which memory switch is crucial, I could not find out.
[
[gradle.log](https://github.com/spotbugs/spotbugs-gradle-plugin/files/2759039/gradle.log)
](url)

**Comment by dovogt** [comment]
Hy,

I have the latest version in use and started the task with --scan. The memory in the gradlew.bat I have increased to 1024MB

https://scans.gradle.com/s/vciemyka5mvk6

Maybe it helps us to continue to find the error :-(

```
@rem Add default JVM options here. So you can use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS = "- Xmx1024m"
```

**Comment by oehme** [comment]
You're changing the memory for the Gradle daemon, which won't help, because spotbugs is run in a different VM. Change the memory settings of Spotbugs intead using `spotbugs.jvmArgs`.

**Comment by shevek** [comment]
Running spotbugs in a separate JVM is a really bad idea from the system resource point of view. It's fine for single threaded builds on a large system, but no good for parallel builds, where we end up spawning a LARGE NUMBER of worker JVMs, and the system runs out of memory at OS level, and the entire build dies.

Please can we make spotbugs in instance-safe, in-process, using the resources allocated to the primary Gradle JVM, so that we can have sane resource allocation and reliable builds.

**Comment by jscancella** [comment]
@dovogt please reopen if this is still an issue
