### ISSUE TITLE
Please sign the published Gradle plugin

### ISSUE THREAD

**Issue by vlsi** [spotbugs/spotbugs-gradle-plugin#888]
Gradle Plugin Publish Plugin signs the plugins since 1.0.0: https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html#sign_artifacts

The signed dependencies are easier to verify.

**Comment by hazendaz** [comment]
Can you raise a PR?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Vladimir Sitnikov ***@***.***>
Sent: Friday, April 28, 2023 2:36:08 AM
To: spotbugs/spotbugs-gradle-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [spotbugs/spotbugs-gradle-plugin] Please sign the published Gradle plugin (Issue #888)


Gradle Plugin Publish Plugin signs the plugins since 1.0.0: https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html#sign_artifacts

The signed dependencies are easier to verify.

**Comment by vlsi** [comment]
Here's a PR: https://github.com/spotbugs/spotbugs-gradle-plugin/pull/889
Here's the same from dependabot: https://github.com/spotbugs/spotbugs-gradle-plugin/pull/876

Would you merge them?

**Comment by hazendaz** [comment]
No code changes needed otherwise?  I seem to recall this update was ignore in the past, don't recall why but thought it had to do with more work.  If not the case sure I'll merge this weekend.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vlsi** [comment]
Upgrading the plugin should be enough
