### ISSUE TITLE
RFC: breaking changes for the coming major release version 6

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs-gradle-plugin#926]
This project is written in Groovy, but it seems that Kotlin is better option to code with Gradle API, so I want to rewrite this project with Kotlin 1.9.0 or later.

I hope that it can mostly keep binary compatibility, but it may not, so it's better to do it as a part of major release (spotbugs-gradle-plugin v6).

Let me know if you think it's nice to introduce more breaking changes, then I'll mark your issue with the milestone for v6.

When you submit PRs for v6, please use the `beta` branch as their base branch. Thank you!

**Comment by hazendaz** [comment]
Trying to understand what you are stating here.  Why does the code need to be groovy or kotlin instead of just java?  Why is the build tool forcing one?  I understand the gradle build itself being groovy or kotlin because that is what it is, but why does the code have to be as well?  I'm coming from maven and maven doesn't force me to use java at all.  So I'm having a hard time understanding why gradle would want users to do such a thing and make it even harder for contributors that don't know groovy well or worse haven't even heard of kotlin.  Ultimately both run on the jvm so to me its making it more complicated in general.

Where I'm coming from this is that the maven plugin is IMO a mess because it was written in groovy and I see zero reason that was done.  It should have been java and then I would not be the only person supporting it.  Most won't even attempt contribute due to groovy.  Nothing ever suggested it should have been that way IMO.  What I do assume is that original author wanted to try something new and this change here feels a lot like the same.

So that leads me to this.  We missed you for a long time here, I get it other life priorities, but for those of us that might be left around, is this going to be easy or hard?  For example, you have foo magic releasing this repo, but appears spotbugs does not have foo magic and was not up to date on how to even remotely release given it stated 'travis' all over and we still don't know how to release it.  I'm sure I can but its a learning curve if no one shows me how at least one time.  So I kind of see a repeat here.  Its great you are back but wondering what the cost this will be to supporters and contributors in general.

**Comment by hazendaz** [comment]
one thing to keep in mind https://youtrack.jetbrains.com/issue/KT-57669/Add-Java-20-to-JvmTarget

jdk 21 is GA next month.  We are getting behind and it does not help if gradle is not keeping up there either.  Kotlin supports 20 now but gradle not.

**Comment by KengoTODA** [comment]
> one thing to keep in mind https://youtrack.jetbrains.com/issue/KT-57669/Add-Java-20-to-JvmTarget
> 
> jdk 21 is GA next month. We are getting behind and it does not help if gradle is not keeping up there either. Kotlin supports 20 now but gradle not.

According to https://github.com/gradle/gradle/pull/25777 Gradle 8.3 should be ready to build on JDK 20.

**Comment by KengoTODA** [comment]
> Why does the code need to be groovy or kotlin instead of just java? 

Gradle provides two options to code its buildscript: Groovy and Kotlin (XML for the case of Maven). And it is going to support Kotlin as the default language to code buildscript, refs https://github.com/gradle/build-tool-roadmap/issues/51

For plugins, we can use any JVM language including Java, Groovy, and Kotlin. But for Groovy and Kotlin, Gradle provides several features to shorten its implementation, like https://github.com/gradle/build-tool-roadmap/issues/50. This would be nice reason to use Groovy or Kotlin instead of Java.

And Groovy is relatively inactive and buggy for years (e.g. #523 and https://discuss.kotlinlang.org/t/bug-cannot-use-kotlin-enum-from-groovy/1521) so I believe that the Kotlin is the best language to choose.

**Comment by hazendaz** [comment]
Thanks will read over this.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bwmeier** [comment]
As part of all of the work for version 6, what will be the minimum Gradle version you will support?  

In the plugins I've written, I've had to drop support for Gradle < 7.6 due to Jackson dependencies, but I don't think you will have that issue.  Still, I had previously had to drop support for Gradle < 7.0 due to Gradle API changes.

My employer's convention plugin auto-applies and configures your plugin, so we definitely want to track these changes.
